theme: jekyll-theme-minimal
title: Immaterial Desires
description: "Cultural Integration of Experimental Digital Art"
#logo: https://dejangrba.github.io/immaterial-desires/Nao-Tokui-2017-The-Latent-Future.jpg
